### ISSUE TITLE
Integrate Dear ImGui

### ISSUE THREAD

**Issue by juli27** [juli27/basaltcpp#7]
- [x] Integrate headless functionality
- [x] add rendering support
- [x] add input support
